/**
 * Auto-mint a dev MCP API key during `bun run init` and write it to .env.local.
 *
 * Closes the loop on the zero-friction agent setup: after the user runs
 * `bun run init`, `.mcp.json` (committed) is already pointing at the local
 * MCP endpoint, and `.env.local` (gitignored) now contains the key. Claude
 * Code picks both up on the next session in this directory — agent works
 * with zero manual config.
 *
 * Idempotent: skips if `INDIGO_MCP_KEY` is already present in `.env.local`.
 * Re-runnable safely.
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import { asc, eq } from 'drizzle-orm';
import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';
import { generateApiKey } from '@/core-api/lib/api-key-service';
import { saasApiKeys } from '@/core-api/schema/api-keys';
import { member } from '@/server/db/schema/organization';
import { MCP_SCOPE } from '@/core/lib/mcp/auth';

const ENV_VAR = 'INDIGO_MCP_KEY';
const KEY_NAME = 'dev-mcp-auto';

export interface MintResult {
  status: 'minted' | 'already-present' | 'no-org' | 'skipped';
  key?: string;
  envPath?: string;
}

/**
 * Mint a dev MCP key for the superadmin's first organization and persist it.
 *
 * @param db                  Drizzle DB instance.
 * @param superadminUserId    The superadmin user id (returned by `ensureSuperadmin`).
 * @param projectRoot         Absolute path to write `.env.local` into.
 */
export async function mintDevMcpKey(
  db: PostgresJsDatabase,
  superadminUserId: string,
  projectRoot: string = process.cwd(),
): Promise<MintResult> {
  const envPath = resolve(projectRoot, '.env.local');

  if (envFileHasKey(envPath, ENV_VAR)) {
    return { status: 'already-present', envPath };
  }

  // Resolve the superadmin's oldest membership — the personal org created at
  // signup (deterministic via ORDER BY). Every user gets one via the
  // user-created hook, so this should always succeed — but if not, we skip
  // gracefully rather than blow up the init flow.
  const [memberRow] = await db
    .select({ organizationId: member.organizationId })
    .from(member)
    .where(eq(member.userId, superadminUserId))
    .orderBy(asc(member.createdAt), asc(member.id))
    .limit(1);

  if (!memberRow) {
    return { status: 'no-org', envPath };
  }

  const { key, hash, prefix } = generateApiKey();

  await db.insert(saasApiKeys).values({
    organizationId: memberRow.organizationId,
    createdBy: superadminUserId,
    name: KEY_NAME,
    keyHash: hash,
    prefix,
    scopes: [MCP_SCOPE],
    status: 'active',
  });

  appendEnvVar(envPath, ENV_VAR, key);

  return { status: 'minted', key, envPath };
}

function envFileHasKey(envPath: string, key: string): boolean {
  if (!existsSync(envPath)) return false;
  const content = readFileSync(envPath, 'utf-8');
  // Match `KEY=` at line start (ignoring leading whitespace), regardless of value.
  return new RegExp(`^\\s*${key}\\s*=`, 'm').test(content);
}

function appendEnvVar(envPath: string, key: string, value: string): void {
  const existing = existsSync(envPath) ? readFileSync(envPath, 'utf-8') : '';
  const sep = existing.length && !existing.endsWith('\n') ? '\n' : '';
  const headerComment =
    `\n# Auto-generated by \`bun run init\` — MCP API key for local Claude Code / Cursor.\n` +
    `# Carries the 'mcp:invoke' scope, acts as the superadmin in their personal org.\n` +
    `# Safe to regenerate: delete the line below and re-run \`bun run init\`.\n`;
  writeFileSync(envPath, `${existing}${sep}${headerComment}${key}=${value}\n`);
}
