/**
 * JSDoc → MCP tool description extraction (runs during `indigo:sync`).
 *
 * Scans router source files for `/** ... *​/` comments directly above
 * procedure definitions and emits `src/generated/procedure-docs.ts` — a
 * `{ 'router.procedure': 'description' }` map the MCP discovery layer uses
 * as a description fallback. This is what makes `search_tools` useful:
 * existing code comments become the search corpus for free.
 *
 * Deliberately NOT promotion: a JSDoc description improves search/describe
 * output, but only an explicit `.meta({ mcp: { description } })` promotes a
 * procedure into the flat tools/list.
 *
 * Best-effort parsing (regex, not AST): covers top-level routers from
 * `_app.ts` + module configs, and one level of nested sub-routers (e.g.
 * `cms.posts.*`). Unmatched procedures just keep their stub description.
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import type { ModuleConfig } from '../../src/core/lib/module/module-config';

const PROCEDURE_HEADS = /^(?:public|protected|staff|superadmin|section)/;

interface RouterSource {
  /** tRPC mount key, dotted for nested (e.g. 'cms.posts'). */
  prefix: string;
  /** Absolute file path. */
  file: string;
}

export function generateProcedureDocs(root: string, outDir: string, modules: ModuleConfig[]): number {
  const sources: RouterSource[] = [
    ...coreRouterSources(root),
    ...modules.flatMap((m) =>
      (m.routers ?? []).map((r) => ({
        prefix: r.key,
        file: resolveImport(root, r.from),
      })),
    ),
  ];

  const docs: Record<string, string> = {};
  const visited = new Set<string>();

  // Breadth-first over routers, following one level of nesting per pass.
  const queue = [...sources];
  while (queue.length > 0) {
    const source = queue.shift()!;
    const visitKey = `${source.prefix}@${source.file}`;
    if (visited.has(visitKey) || !existsSync(source.file)) continue;
    visited.add(visitKey);

    const content = readFileSync(source.file, 'utf-8');
    extractProcedureDocs(content, source.prefix, docs);
    queue.push(...extractNestedRouters(content, source));
  }

  const entries = Object.entries(docs)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join('\n');

  const header = '// AUTO-GENERATED by `bun run indigo:sync` — DO NOT EDIT\n// JSDoc descriptions extracted from router files (see scripts/indigo/procedure-docs.ts)\n';
  writeFileSync(
    resolve(outDir, 'procedure-docs.ts'),
    `${header}\nexport const PROCEDURE_DOCS: Record<string, string> = {\n${entries}\n};\n`,
  );

  return Object.keys(docs).length;
}

/** Parse _app.ts for `key: someRouter` entries + their import paths. */
function coreRouterSources(root: string): RouterSource[] {
  const appPath = resolve(root, 'src/server/routers/_app.ts');
  if (!existsSync(appPath)) return [];
  const content = readFileSync(appPath, 'utf-8');

  const imports = new Map<string, string>();
  for (const m of content.matchAll(/import \{ (\w+) \} from '(\.[^']+)';/g)) {
    imports.set(m[1], m[2]);
  }

  const sources: RouterSource[] = [];
  for (const m of content.matchAll(/^\s{2}(\w+): (\w+),$/gm)) {
    const relPath = imports.get(m[2]);
    if (!relPath) continue; // moduleRouters spread etc.
    sources.push({ prefix: m[1], file: resolveRelative(dirname(appPath), relPath) });
  }
  return sources;
}

/** Extract `/** doc *​/ name: xProcedure` pairs into the docs map. */
function extractProcedureDocs(content: string, prefix: string, docs: Record<string, string>): void {
  for (const m of content.matchAll(/\/\*\*([\s\S]*?)\*\/\s*\n\s*(\w+):\s*(\w+)/g)) {
    const [, rawDoc, name, head] = m;
    if (!PROCEDURE_HEADS.test(head)) continue;
    const doc = cleanJsDoc(rawDoc);
    if (doc) docs[`${prefix}.${name}`] = doc;
  }
}

/** Find `key: nestedRouter` entries whose router is imported locally. */
function extractNestedRouters(content: string, parent: RouterSource): RouterSource[] {
  const imports = new Map<string, string>();
  for (const m of content.matchAll(/import \{ (\w+) \} from '(\.[^']+)';/g)) {
    imports.set(m[1], m[2]);
  }
  const nested: RouterSource[] = [];
  for (const m of content.matchAll(/^\s{2}(\w+): (\w+Router),$/gm)) {
    const relPath = imports.get(m[2]);
    if (!relPath) continue;
    nested.push({
      prefix: `${parent.prefix}.${m[1]}`,
      file: resolveRelative(dirname(parent.file), relPath),
    });
  }
  return nested;
}

/** First paragraph of a JSDoc block, cleaned and capped. */
function cleanJsDoc(raw: string): string {
  const text = raw
    .split('\n')
    .map((line) => line.replace(/^\s*\*\s?/, '').trim())
    .filter((line) => !line.startsWith('@')) // drop tags
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim();
  if (!text) return '';
  return text.length > 240 ? `${text.slice(0, 237)}...` : text;
}

function resolveImport(root: string, importPath: string): string {
  const base = importPath.startsWith('@/')
    ? resolve(root, 'src', importPath.slice(2))
    : resolve(root, importPath);
  return withTsExtension(base);
}

function resolveRelative(fromDir: string, relPath: string): string {
  return withTsExtension(resolve(fromDir, relPath));
}

function withTsExtension(base: string): string {
  if (existsSync(`${base}.ts`)) return `${base}.ts`;
  if (existsSync(resolve(base, 'index.ts'))) return resolve(base, 'index.ts');
  return `${base}.ts`;
}
