import type { ModuleConfig } from '@/core/lib/module/module-config';

const config: ModuleConfig = {
  id: 'core-store',
  category: 'product',
  routers: [
    { name: 'storeProductsRouter', key: 'storeProducts', from: '@/core-store/routers/products' },
    { name: 'storeCartRouter', key: 'storeCart', from: '@/core-store/routers/cart' },
    { name: 'storeCheckoutRouter', key: 'storeCheckout', from: '@/core-store/routers/checkout' },
    { name: 'storeOrdersRouter', key: 'storeOrders', from: '@/core-store/routers/orders' },
    { name: 'storeAdminOrdersRouter', key: 'storeAdminOrders', from: '@/core-store/routers/admin-orders' },
    { name: 'storeWishlistRouter', key: 'storeWishlist', from: '@/core-store/routers/wishlists' },
    { name: 'storeDiscountsRouter', key: 'storeDiscounts', from: '@/core-store/routers/discounts' },
    { name: 'storeReviewsRouter', key: 'storeReviews', from: '@/core-store/routers/reviews' },
    { name: 'storeRelationsRouter', key: 'storeRelations', from: '@/core-store/routers/relations' },
    { name: 'storeAttributesRouter', key: 'storeAttributes', from: '@/core-store/routers/attributes' },
    { name: 'storeAddressesRouter', key: 'storeAddresses', from: '@/core-store/routers/addresses' },
    { name: 'storeAnalyticsRouter', key: 'storeAnalytics', from: '@/core-store/routers/analytics' },
    { name: 'storeFulfillmentRouter', key: 'storeFulfillment', from: '@/core-store/routers/fulfillment' },
    { name: 'storeReturnsRouter', key: 'storeReturns', from: '@/core-store/routers/returns' },
    { name: 'storeAlertsRouter', key: 'storeAlerts', from: '@/core-store/routers/alerts' },
    { name: 'storeAdminRouter', key: 'storeAdmin', from: '@/core-store/routers/store-admin' },
  ],
  schema: [
    '@/core-store/schema/products',
    '@/core-store/schema/orders',
    '@/core-store/schema/shipping-tax',
    '@/core-store/schema/wishlists',
    '@/core-store/schema/discount-codes',
    '@/core-store/schema/reviews',
    '@/core-store/schema/relations',
    '@/core-store/schema/attributes',
    '@/core-store/schema/currency',
    '@/core-store/schema/inventory',
    '@/core-store/schema/fulfillment',
    '@/core-store/schema/returns',
    '@/core-store/schema/bundles',
    '@/core-store/schema/alerts',
  ],
  serverInit: [
    '@/config/deps/store-deps',
  ],
  jobs: [],
  seed: [
    { name: 'seedStore', from: '@/core-store/seed', label: 'Store demo products, shipping zones & tax rates', hasDataCheck: 'hasStoreData' },
  ],
  layoutWidgets: [
    { name: 'CartWidget', from: '@/core-store/components/cart/CartWidget', slot: 'header' },
  ],
  pageWidgets: [],
  navItems: [
    { groupId: 'content', name: 'Store', href: '/dashboard/store', icon: 'ShoppingBag' },
  ],
  sitemapFetchers: [
    { name: 'storeSitemapFetchers', from: '@/core-store/lib/sitemap-fetchers' },
  ],
  projectFiles: [
    'config/deps/store-deps.ts',
    'config/store-pricing.ts',
    'emails/en/order-confirmation.html',
    'emails/en/order-shipped.html',
    'emails/en/order-processing.html',
    'emails/en/order-delivered.html',
    'emails/en/order-cancelled.html',
    'emails/en/order-refunded.html',
    'emails/en/abandoned-cart.html',
    'emails/en/review-request.html',
    'emails/en/back-in-stock.html',
    'app/(public)/store/page.tsx',
    'app/(public)/store/client.tsx',
    'app/(public)/store/[slug]/page.tsx',
    'app/(public)/store/[slug]/client.tsx',
    'app/(public)/store/[slug]/ProductDetailClient.tsx',
    'app/(public)/store/loading.tsx',
    'app/(public)/store/[slug]/loading.tsx',
    'app/(public)/cart/page.tsx',
    'app/(public)/cart/CartPageClient.tsx',
    'app/(public)/cart/loading.tsx',
    'app/(public)/checkout/page.tsx',
    'app/(public)/checkout/CheckoutForm.tsx',
    'app/(public)/order-confirmation/page.tsx',
    'app/(public)/account/orders/page.tsx',
    'app/(public)/account/orders/[id]/page.tsx',
    'app/(public)/account/orders/[id]/OrderDetailView.tsx',
    'app/(public)/account/wishlist/page.tsx',
    'app/(public)/account/addresses/page.tsx',
    'app/api/webhooks/store/route.ts',
    'app/api/webhooks/stripe/__tests__/route.test.ts',
    'app/dashboard/(panel)/store/page.tsx',
    'app/dashboard/(panel)/store/new/page.tsx',
    'app/dashboard/(panel)/store/[id]/page.tsx',
    'app/dashboard/(panel)/store/orders/page.tsx',
    'app/dashboard/(panel)/store/orders/[id]/page.tsx',
    'app/dashboard/(panel)/store/discounts/page.tsx',
    'app/dashboard/(panel)/store/reviews/page.tsx',
    'app/dashboard/(panel)/store/attributes/page.tsx',
  ],
};

export default config;
