import type { ModuleConfig } from '@/core/lib/module/module-config';

const config: ModuleConfig = {
  id: 'core-store',
  routers: [
    { name: 'storeProductsRouter', key: 'storeProducts', from: '@/core-store/routers/products' },
    { name: 'storeCartRouter', key: 'storeCart', from: '@/core-store/routers/cart' },
    { name: 'storeCheckoutRouter', key: 'storeCheckout', from: '@/core-store/routers/checkout' },
    { name: 'storeOrdersRouter', key: 'storeOrders', from: '@/core-store/routers/orders' },
    { name: 'storeAdminOrdersRouter', key: 'storeAdminOrders', from: '@/core-store/routers/admin-orders' },
    { name: 'storeWishlistRouter', key: 'storeWishlist', from: '@/core-store/routers/wishlists' },
    { name: 'storeDiscountsRouter', key: 'storeDiscounts', from: '@/core-store/routers/discounts' },
    { name: 'storeReviewsRouter', key: 'storeReviews', from: '@/core-store/routers/reviews' },
    { name: 'storeRelationsRouter', key: 'storeRelations', from: '@/core-store/routers/relations' },
    { name: 'storeAttributesRouter', key: 'storeAttributes', from: '@/core-store/routers/attributes' },
    { name: 'storeAddressesRouter', key: 'storeAddresses', from: '@/core-store/routers/addresses' },
  ],
  schema: [
    '@/core-store/schema/products',
    '@/core-store/schema/orders',
    '@/core-store/schema/shipping-tax',
    '@/core-store/schema/wishlists',
    '@/core-store/schema/discount-codes',
    '@/core-store/schema/reviews',
    '@/core-store/schema/relations',
    '@/core-store/schema/attributes',
  ],
  serverInit: [
    '@/config/store-deps',
  ],
  jobs: [],
  seed: [
    { name: 'seedStore', from: '@/core-store/seed', label: 'Store demo products, shipping zones & tax rates', hasDataCheck: 'hasStoreData' },
  ],
  layoutWidgets: [],
  pageWidgets: [],
  navItems: [
    { groupId: 'content', name: 'Store', href: '/dashboard/store', icon: 'ShoppingBag' },
  ],
  projectFiles: [
    'config/store-deps.ts',
    'emails/order-confirmation.html',
    'emails/order-shipped.html',
    'emails/order-processing.html',
    'emails/order-delivered.html',
    'emails/order-cancelled.html',
    'emails/order-refunded.html',
    'emails/abandoned-cart.html',
    'app/(public)/store/page.tsx',
    'app/(public)/store/client.tsx',
    'app/(public)/store/[slug]/page.tsx',
    'app/(public)/store/[slug]/client.tsx',
    'app/(public)/cart/page.tsx',
    'app/(public)/checkout/page.tsx',
    'app/(public)/account/orders/page.tsx',
    'app/(public)/account/orders/[id]/page.tsx',
    'app/(public)/account/wishlist/page.tsx',
    'app/dashboard/(panel)/store/page.tsx',
    'app/dashboard/(panel)/store/orders/page.tsx',
    'app/dashboard/(panel)/store/discounts/page.tsx',
    'app/dashboard/(panel)/store/reviews/page.tsx',
    'app/dashboard/(panel)/store/attributes/page.tsx',
  ],
};

export default config;
