/**
 * Module sync — reads indigo.config.ts and generates glue files.
 *
 * Usage: bun run indigo:sync
 *
 * Generated files (DO NOT EDIT):
 *   src/generated/module-routers.ts   — tRPC router assembly
 *   src/generated/module-schema.ts    — schema re-exports for Drizzle
 *   src/generated/module-server.ts    — deps + jobs registration
 *   src/generated/module-widgets.ts   — layout widget components
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve } from 'path';
import type { ModuleConfig } from '../src/core/lib/module-config';

const HEADER = '// AUTO-GENERATED by `bun run indigo:sync` — DO NOT EDIT\n// Edit indigo.config.ts and re-run sync\n';

const root = process.cwd();
const outDir = resolve(root, 'src/generated');

async function main() {
  // Dynamic import of the config
  const configModule = await import(resolve(root, 'indigo.config.ts'));
  const modules: ModuleConfig[] = configModule.default;

  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  generateRouters(modules);
  generateSchema(modules);
  generateServer(modules);
  generateWidgets(modules);
  generateSeeds(modules);

  console.log(`Module sync complete — ${modules.length} modules registered`);
  console.log('  src/generated/module-routers.ts');
  console.log('  src/generated/module-schema.ts');
  console.log('  src/generated/module-server.ts');
  console.log('  src/generated/module-widgets.ts');
  console.log('  src/generated/module-seeds.ts');
}

function generateRouters(modules: ModuleConfig[]) {
  const routers = modules.flatMap((m) => m.routers);
  if (routers.length === 0) {
    writeFileSync(
      resolve(outDir, 'module-routers.ts'),
      `${HEADER}\n// No module routers registered\nexport const moduleRouters = {} as const;\n`,
    );
    return;
  }

  const imports = routers
    .map((r) => `import { ${r.name} } from '${r.from}';`)
    .join('\n');

  const entries = routers
    .map((r) => `  ${r.key}: ${r.name},`)
    .join('\n');

  writeFileSync(
    resolve(outDir, 'module-routers.ts'),
    `${HEADER}\n${imports}\n\nexport const moduleRouters = {\n${entries}\n} as const;\n`,
  );
}

function generateSchema(modules: ModuleConfig[]) {
  const schemas = modules.flatMap((m) => m.schema);

  const exports = schemas
    .map((s) => `export * from '${s}';`)
    .join('\n');

  writeFileSync(
    resolve(outDir, 'module-schema.ts'),
    `${HEADER}\n${exports || '// No module schemas registered'}\n`,
  );
}

function generateServer(modules: ModuleConfig[]) {
  const inits = modules.flatMap((m) => m.serverInit);
  const jobs = modules.flatMap((m) => m.jobs);

  const initImports = inits
    .map((s) => `  await import('${s}');`)
    .join('\n');

  const jobImports = jobs
    .map((j) => `  const { ${j.name} } = await import('${j.from}');`)
    .join('\n');

  const jobCalls = jobs
    .map((j) => `  ${j.name}();`)
    .join('\n');

  const content = `${HEADER}
/**
 * Initialize module dependencies and registrations.
 * Called once at server startup before workers start.
 */
export async function initModuleDeps(): Promise<void> {
${initImports || '  // No module deps to initialize'}
}

/**
 * Start module background workers.
 * Called when server role includes workers.
 */
export async function startModuleWorkers(): Promise<void> {
${jobImports || '  // No module workers to start'}
${jobCalls || ''}
}
`;

  writeFileSync(resolve(outDir, 'module-server.ts'), content);
}

function generateWidgets(modules: ModuleConfig[]) {
  const widgets = modules.flatMap((m) => m.layoutWidgets);

  if (widgets.length === 0) {
    writeFileSync(
      resolve(outDir, 'module-widgets.ts'),
      `${HEADER}\nimport type { ComponentType } from 'react';\n\nexport const PUBLIC_LAYOUT_WIDGETS: ComponentType[] = [];\n`,
    );
    return;
  }

  const imports = widgets
    .map((w) => `import { ${w.name} } from '${w.from}';`)
    .join('\n');

  const entries = widgets
    .map((w) => `  ${w.name},`)
    .join('\n');

  writeFileSync(
    resolve(outDir, 'module-widgets.ts'),
    `${HEADER}\nimport type { ComponentType } from 'react';\n\n${imports}\n\nexport const PUBLIC_LAYOUT_WIDGETS: ComponentType[] = [\n${entries}\n];\n`,
  );
}

function generateSeeds(modules: ModuleConfig[]) {
  const seeds = modules.flatMap((m) => m.seed ?? []);

  if (seeds.length === 0) {
    writeFileSync(
      resolve(outDir, 'module-seeds.ts'),
      `${HEADER}\nimport type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';\n\nexport interface ModuleSeed {\n  label: string;\n  fn: (db: PostgresJsDatabase, superadminUserId: string) => Promise<{ userIds?: string[]; orgIds?: string[] }>;\n}\n\nexport const MODULE_SEEDS: ModuleSeed[] = [];\n`,
    );
    return;
  }

  const imports = seeds
    .map((s) => `import { ${s.name} } from '${s.from}';`)
    .join('\n');

  const entries = seeds
    .map((s) => `  { label: '${s.label}', fn: ${s.name} },`)
    .join('\n');

  const content = `${HEADER}
import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';

${imports}

export interface SeedContext {
  userIds: string[];
  orgIds: string[];
}

export interface ModuleSeed {
  label: string;
  fn: (db: PostgresJsDatabase, superadminUserId: string, context?: SeedContext) => Promise<{ userIds?: string[]; orgIds?: string[] }>;
}

export const MODULE_SEEDS: ModuleSeed[] = [
${entries}
];
`;

  writeFileSync(resolve(outDir, 'module-seeds.ts'), content);
}

main().catch((err) => {
  console.error('Module sync failed:', err);
  process.exit(1);
});
