/**
 * Module sync — reads indigo.config.ts and generates glue files.
 *
 * Usage: bun run indigo:sync
 *
 * Generated files (DO NOT EDIT):
 *   src/generated/module-routers.ts   — tRPC router assembly
 *   src/generated/module-schema.ts    — schema re-exports for Drizzle
 *   src/generated/module-server.ts    — deps + jobs registration
 *   src/generated/module-widgets.ts   — layout widget components
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve } from 'path';
import type { ModuleConfig } from '../src/core/lib/module/module-config';

const HEADER = '// AUTO-GENERATED by `bun run indigo:sync` — DO NOT EDIT\n// Edit indigo.config.ts and re-run sync\n';

const root = process.cwd();
const outDir = resolve(root, 'src/generated');

async function main() {
  // Dynamic import of the config
  const configModule = await import(resolve(root, 'indigo.config.ts'));
  const modules: ModuleConfig[] = configModule.default;

  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  generateRouters(modules);
  generateSchema(modules);
  generateServer(modules);
  generateWidgets(modules);
  generatePageWidgets(modules);
  generateSeeds(modules);
  generateNav(modules);

  console.log(`Module sync complete — ${modules.length} modules registered`);
  console.log('  src/generated/module-routers.ts');
  console.log('  src/generated/module-schema.ts');
  console.log('  src/generated/module-server.ts');
  console.log('  src/generated/module-widgets.ts');
  console.log('  src/generated/module-page-widgets.ts');
  console.log('  src/generated/module-seeds.ts');
  console.log('  src/generated/module-nav.ts');
}

function generateRouters(modules: ModuleConfig[]) {
  const routers = modules.flatMap((m) => m.routers);
  if (routers.length === 0) {
    writeFileSync(
      resolve(outDir, 'module-routers.ts'),
      `${HEADER}\n// No module routers registered\nexport const moduleRouters = {} as const;\n`,
    );
    return;
  }

  const imports = routers
    .map((r) => `import { ${r.name} } from '${r.from}';`)
    .join('\n');

  const entries = routers
    .map((r) => `  ${r.key}: ${r.name},`)
    .join('\n');

  writeFileSync(
    resolve(outDir, 'module-routers.ts'),
    `${HEADER}\n${imports}\n\nexport const moduleRouters = {\n${entries}\n} as const;\n`,
  );
}

function generateSchema(modules: ModuleConfig[]) {
  const schemas = modules.flatMap((m) => m.schema);
  const overrides = modules.flatMap((m) => m.overridableSchema ?? []);

  // Check which overrides have project-level files
  const overrideDir = resolve(root, 'src/schema/overrides');
  const overriddenPaths = new Set<string>();

  const overrideExports: string[] = [];
  for (const override of overrides) {
    const overrideFile = resolve(overrideDir, `${override.name}.ts`);
    if (existsSync(overrideFile)) {
      // Project has an override — use it instead of module default
      overriddenPaths.add(override.modulePath);
      overrideExports.push(`export * from '@/schema/overrides/${override.name}';`);
    }
  }

  const exports = schemas
    .map((s) => {
      if (overriddenPaths.has(s)) {
        // This schema has a project override — skip module version
        return `// Overridden by project: ${s}`;
      }
      return `export * from '${s}';`;
    })
    .join('\n');

  const allExports = [exports, ...overrideExports].filter(Boolean).join('\n');

  writeFileSync(
    resolve(outDir, 'module-schema.ts'),
    `${HEADER}\n${allExports || '// No module schemas registered'}\n`,
  );
}

function generateServer(modules: ModuleConfig[]) {
  const inits = modules.flatMap((m) => m.serverInit);
  const jobs = modules.flatMap((m) => m.jobs);

  const initImports = inits
    .map((s) => {
      const mod = s.match(/(?:@\/config\/|@\/core-)([^/]+)/)?.[1] ?? s;
      return `  try { await import('${s}'); } catch (e) { console.error('[module:${mod}] init failed:', e); throw e; }`;
    })
    .join('\n');

  const jobImports = jobs
    .map((j) => `  const { ${j.name} } = await import('${j.from}');`)
    .join('\n');

  const jobCalls = jobs
    .map((j) => `  ${j.name}();`)
    .join('\n');

  const content = `${HEADER}
/**
 * Initialize module dependencies and registrations.
 * Called once at server startup before workers start.
 */
export async function initModuleDeps(): Promise<void> {
${initImports || '  // No module deps to initialize'}
}

/**
 * Start module background workers.
 * Called when server role includes workers.
 */
export async function startModuleWorkers(): Promise<void> {
${jobImports || '  // No module workers to start'}
${jobCalls || ''}
}
`;

  writeFileSync(resolve(outDir, 'module-server.ts'), content);
}

function generateWidgets(modules: ModuleConfig[]) {
  const widgets = modules.flatMap((m) => m.layoutWidgets);

  if (widgets.length === 0) {
    writeFileSync(
      resolve(outDir, 'module-widgets.ts'),
      `${HEADER}\nimport type { ComponentType } from 'react';\n\nexport const PUBLIC_LAYOUT_WIDGETS: ComponentType[] = [];\n`,
    );
    return;
  }

  const imports = widgets
    .map((w) => `import { ${w.name} } from '${w.from}';`)
    .join('\n');

  const entries = widgets
    .map((w) => `  ${w.name},`)
    .join('\n');

  writeFileSync(
    resolve(outDir, 'module-widgets.ts'),
    `${HEADER}\nimport type { ComponentType } from 'react';\n\n${imports}\n\nexport const PUBLIC_LAYOUT_WIDGETS: ComponentType[] = [\n${entries}\n];\n`,
  );
}

function generatePageWidgets(modules: ModuleConfig[]) {
  const widgets = modules.flatMap((m) => m.pageWidgets ?? []);
  const emptyContent = `${HEADER}\nimport type { ComponentType } from 'react';\n\nexport const PAGE_WIDGETS: Record<string, ComponentType[]> = {};\n`;

  if (widgets.length === 0) {
    writeFileSync(resolve(outDir, 'module-page-widgets.ts'), emptyContent);
    return;
  }

  // Group by slot
  const slots = new Map<string, typeof widgets>();
  for (const w of widgets) {
    const list = slots.get(w.slot) ?? [];
    list.push(w);
    slots.set(w.slot, list);
  }

  const imports = widgets
    .map((w) => `import { ${w.name} } from '${w.from}';`)
    .join('\n');

  const entries = [...slots.entries()]
    .map(([slot, items]) => `  '${slot}': [${items.map((w) => w.name).join(', ')}],`)
    .join('\n');

  writeFileSync(
    resolve(outDir, 'module-page-widgets.ts'),
    `${HEADER}\nimport type { ComponentType } from 'react';\n\n${imports}\n\nexport const PAGE_WIDGETS: Record<string, ComponentType[]> = {\n${entries}\n};\n`,
  );
}

function generateSeeds(modules: ModuleConfig[]) {
  const seeds = modules.flatMap((m) => m.seed ?? []);

  if (seeds.length === 0) {
    writeFileSync(
      resolve(outDir, 'module-seeds.ts'),
      `${HEADER}\nimport type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';\n\nexport interface ModuleSeed {\n  label: string;\n  fn: (db: PostgresJsDatabase, superadminUserId: string) => Promise<{ userIds?: string[]; orgIds?: string[] }>;\n}\n\nexport const MODULE_SEEDS: ModuleSeed[] = [];\n`,
    );
    return;
  }

  const importNames = new Set<string>();
  const importLines: string[] = [];

  for (const s of seeds) {
    if (!importNames.has(s.name)) {
      const extras = s.hasDataCheck ? `, ${s.hasDataCheck}` : '';
      importLines.push(`import { ${s.name}${extras} } from '${s.from}';`);
      importNames.add(s.name);
      if (s.hasDataCheck) importNames.add(s.hasDataCheck);
    }
  }

  const imports = importLines.join('\n');

  const entries = seeds
    .map((s) => {
      const hasDataPart = s.hasDataCheck ? `, hasData: ${s.hasDataCheck}` : '';
      return `  { label: '${s.label}', fn: ${s.name}${hasDataPart} },`;
    })
    .join('\n');

  const content = `${HEADER}
import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';

${imports}

export interface SeedContext {
  userIds: string[];
  orgIds: string[];
}

export interface ModuleSeed {
  label: string;
  fn: (db: PostgresJsDatabase, superadminUserId: string, context?: SeedContext) => Promise<{ userIds?: string[]; orgIds?: string[] }>;
  hasData?: (db: PostgresJsDatabase) => Promise<boolean>;
}

export const MODULE_SEEDS: ModuleSeed[] = [
${entries}
];
`;

  writeFileSync(resolve(outDir, 'module-seeds.ts'), content);
}

function generateNav(modules: ModuleConfig[]) {
  const navItems = modules.flatMap((m) => m.navItems ?? []);

  if (navItems.length === 0) {
    writeFileSync(
      resolve(outDir, 'module-nav.ts'),
      `${HEADER}\nexport interface ModuleNavItem {\n  groupId: string;\n  name: string;\n  href: string;\n  icon: string;\n}\n\nexport const MODULE_NAV_ITEMS: ModuleNavItem[] = [];\n`,
    );
    return;
  }

  const entries = navItems
    .map((n) => `  { groupId: '${n.groupId}', name: '${n.name}', href: '${n.href}', icon: '${n.icon}' },`)
    .join('\n');

  const content = `${HEADER}
export interface ModuleNavItem {
  groupId: string;
  name: string;
  href: string;
  icon: string;
}

export const MODULE_NAV_ITEMS: ModuleNavItem[] = [
${entries}
];
`;

  writeFileSync(resolve(outDir, 'module-nav.ts'), content);
}

main().catch((err) => {
  console.error('Module sync failed:', err);
  process.exit(1);
});
