/**
 * Module sync — reads indigo.config.ts and generates glue files.
 *
 * Usage: bun run indigo:sync
 *
 * Generated files (DO NOT EDIT):
 *   src/generated/module-routers.ts           — tRPC router assembly
 *   src/generated/module-schema.ts            — schema re-exports for Drizzle
 *   src/generated/module-server.ts            — deps + jobs registration
 *   src/generated/module-widgets.ts           — layout widget components
 *   src/generated/module-dashboard-widgets.ts — dashboard widget registry
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve } from 'path';
import type { ModuleConfig } from '../src/core/lib/module/module-config';
import { generateProcedureDocs } from './indigo/procedure-docs';

const HEADER = '// AUTO-GENERATED by `bun run indigo:sync` — DO NOT EDIT\n// Edit indigo.config.ts and re-run sync\n';

const root = process.cwd();
const outDir = resolve(root, 'src/generated');

async function main() {
  // Dynamic import of the config
  const configModule = await import(resolve(root, 'indigo.config.ts'));
  const modules: ModuleConfig[] = configModule.default;

  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  generateRouters(modules);
  generateSchema(modules);
  generateServer(modules);
  generateWidgets(modules);
  generatePageWidgets(modules);
  generateDashboardWidgets(modules);
  generateSitemapFetchers(modules);
  generateContentSlots(modules);
  generateSeeds(modules);
  generateNav(modules);
  generateMcp(modules);
  const docCount = generateProcedureDocs(root, outDir, modules);

  console.log(`Module sync complete — ${modules.length} modules registered, ${docCount} procedure docs extracted`);
  console.log('  src/generated/module-routers.ts');
  console.log('  src/generated/module-schema.ts');
  console.log('  src/generated/module-server.ts');
  console.log('  src/generated/module-widgets.ts');
  console.log('  src/generated/module-page-widgets.ts');
  console.log('  src/generated/module-dashboard-widgets.ts');
  console.log('  src/generated/module-seeds.ts');
  console.log('  src/generated/module-nav.ts');
  console.log('  src/generated/module-mcp.ts');
  console.log('  src/generated/procedure-docs.ts');
}

function generateRouters(modules: ModuleConfig[]) {
  const routers = modules.flatMap((m) => m.routers);
  if (routers.length === 0) {
    writeFileSync(
      resolve(outDir, 'module-routers.ts'),
      `${HEADER}\n// No module routers registered\nexport const moduleRouters = {} as const;\n`,
    );
    return;
  }

  const imports = routers
    .map((r) => `import { ${r.name} } from '${r.from}';`)
    .join('\n');

  const entries = routers
    .map((r) => `  ${r.key}: ${r.name},`)
    .join('\n');

  writeFileSync(
    resolve(outDir, 'module-routers.ts'),
    `${HEADER}\n${imports}\n\nexport const moduleRouters = {\n${entries}\n} as const;\n`,
  );
}

function generateSchema(modules: ModuleConfig[]) {
  const schemas = modules.flatMap((m) => m.schema);
  const overrides = modules.flatMap((m) => m.overridableSchema ?? []);

  // Check which overrides have project-level files
  const overrideDir = resolve(root, 'src/schema/overrides');
  const overriddenPaths = new Set<string>();

  const overrideExports: string[] = [];
  for (const override of overrides) {
    const overrideFile = resolve(overrideDir, `${override.name}.ts`);
    if (existsSync(overrideFile)) {
      // Project has an override — use it instead of module default
      overriddenPaths.add(override.modulePath);
      overrideExports.push(`export * from '@/schema/overrides/${override.name}';`);
    }
  }

  const exports = schemas
    .map((s) => {
      if (overriddenPaths.has(s)) {
        // This schema has a project override — skip module version
        return `// Overridden by project: ${s}`;
      }
      return `export * from '${s}';`;
    })
    .join('\n');

  const allExports = [exports, ...overrideExports].filter(Boolean).join('\n');

  writeFileSync(
    resolve(outDir, 'module-schema.ts'),
    `${HEADER}\n${allExports || '// No module schemas registered'}\n`,
  );
}

function generateServer(modules: ModuleConfig[]) {
  const inits = modules.flatMap((m) => m.serverInit);
  const jobs = modules.flatMap((m) => m.jobs);

  const initImports = inits
    .map((s) => {
      const mod = s.match(/(?:@\/config\/|@\/core-)([^/]+)/)?.[1] ?? s;
      return `  try { await import('${s}'); } catch (e) { console.error('[module:${mod}] init failed:', e); throw e; }`;
    })
    .join('\n');

  const jobImports = jobs
    .map((j) => `  const { ${j.name} } = await import('${j.from}');`)
    .join('\n');

  const jobCalls = jobs
    .map((j) => `  ${j.name}();`)
    .join('\n');

  const content = `${HEADER}
/**
 * Initialize module dependencies and registrations.
 * Called once at server startup before workers start.
 */
export async function initModuleDeps(): Promise<void> {
${initImports || '  // No module deps to initialize'}
}

/**
 * Start module background workers.
 * Called when server role includes workers.
 */
export async function startModuleWorkers(): Promise<void> {
${jobImports || '  // No module workers to start'}
${jobCalls || ''}
}
`;

  writeFileSync(resolve(outDir, 'module-server.ts'), content);
}

function generateWidgets(modules: ModuleConfig[]) {
  const all = modules.flatMap((m) => m.layoutWidgets);
  const layoutWidgets = all.filter((w) => (w.slot ?? 'layout') === 'layout');
  const headerWidgets = all.filter((w) => w.slot === 'header');

  const typeBlock =
    `import type { ComponentType } from 'react';\n\n` +
    `export interface LayoutWidgetEntry {\n` +
    `  /** The widget component. */\n` +
    `  Component: ComponentType;\n` +
    `  /** If set, only render when the user has granted consent for this category. */\n` +
    `  consentCategory?: string;\n` +
    `}\n`;

  const imports = all.map((w) => `import { ${w.name} } from '${w.from}';`).join('\n');

  const renderEntries = (widgets: typeof all) =>
    widgets
      .map((w) =>
        w.consentCategory
          ? `  { Component: ${w.name}, consentCategory: '${w.consentCategory}' },`
          : `  { Component: ${w.name} },`,
      )
      .join('\n');

  const layoutBlock =
    layoutWidgets.length === 0
      ? `export const PUBLIC_LAYOUT_WIDGETS: LayoutWidgetEntry[] = [];`
      : `export const PUBLIC_LAYOUT_WIDGETS: LayoutWidgetEntry[] = [\n${renderEntries(layoutWidgets)}\n];`;

  // Header-slot widgets render in the public header's actions area.
  const headerBlock =
    headerWidgets.length === 0
      ? `export const HEADER_WIDGETS: LayoutWidgetEntry[] = [];`
      : `export const HEADER_WIDGETS: LayoutWidgetEntry[] = [\n${renderEntries(headerWidgets)}\n];`;

  writeFileSync(
    resolve(outDir, 'module-widgets.ts'),
    `${HEADER}\n${typeBlock}${imports ? `\n${imports}\n` : ''}\n${layoutBlock}\n\n${headerBlock}\n`,
  );
}

function generateSitemapFetchers(modules: ModuleConfig[]) {
  const fetchers = modules.flatMap((m) => m.sitemapFetchers ?? []);

  if (fetchers.length === 0) {
    writeFileSync(
      resolve(outDir, 'module-sitemap.ts'),
      `${HEADER}\nimport type { SitemapFetcher } from '@/core/lib/seo/sitemap';\n\nexport const MODULE_SITEMAP_FETCHERS: SitemapFetcher[] = [];\n`,
    );
    return;
  }

  const imports = fetchers.map((f) => `import { ${f.name} } from '${f.from}';`).join('\n');
  const names = fetchers.map((f) => `  ${f.name},`).join('\n');

  writeFileSync(
    resolve(outDir, 'module-sitemap.ts'),
    `${HEADER}\nimport type { SitemapFetcher } from '@/core/lib/seo/sitemap';\n${imports}\n\n// Entries may be a single fetcher or an array — flattened here.\nexport const MODULE_SITEMAP_FETCHERS: SitemapFetcher[] = [\n${names}\n].flat();\n`,
  );
}

function generateContentSlots(modules: ModuleConfig[]) {
  const entries = modules.flatMap((m) => m.contentSlots ?? []);
  const hookEntry = entries.find((e) => e.slot === 'showcase-comments');
  const slotEntries = entries.filter((e) => e.slot !== 'showcase-comments');

  const slotNames = [...new Set(slotEntries.map((e) => e.slot))];
  const imports = slotEntries.map((e) => `import { ${e.name} } from '${e.from}';`).join('\n');
  const record = slotNames
    .map((slot) => {
      const names = slotEntries.filter((e) => e.slot === slot).map((e) => e.name).join(', ');
      return `  '${slot}': [${names}],`;
    })
    .join('\n');

  const hookBlock = hookEntry
    ? `export { ${hookEntry.name} } from '${hookEntry.from}';`
    : `/** No comments module installed — inert fallback keeps ShowcaseFeed's API stable. */
export function useShowcaseComments(_itemIds: string[]): {
  counts: Record<string, number>;
  openPanel: (id: string) => void;
  isPanelOpen: boolean;
  panel: ReactNode;
} {
  return { counts: {}, openPanel: () => {}, isPanelOpen: false, panel: null };
}`;

  const typeImports = hookEntry ? 'ComponentType' : 'ComponentType, ReactNode';

  writeFileSync(
    resolve(outDir, 'content-slots.tsx'),
    `${HEADER}
import type { ${typeImports} } from 'react';
${imports ? `${imports}\n` : ''}
export interface ContentSlotProps {
  targetType: string;
  targetId: string;
}

/** Components contributed to named slots by installed modules. */
export const CONTENT_SLOTS: Record<string, ComponentType<ContentSlotProps>[]> = {
${record}
};

/** Renders every component registered for a slot; nothing when the slot is empty. */
export function ContentSlot({ slot, ...props }: ContentSlotProps & { slot: string }) {
  const components = CONTENT_SLOTS[slot];
  if (!components?.length) return null;
  return (
    <>
      {components.map((C, i) => (
        <C key={i} {...props} />
      ))}
    </>
  );
}

${hookBlock}
`,
  );
}

function generatePageWidgets(modules: ModuleConfig[]) {
  const widgets = modules.flatMap((m) => m.pageWidgets ?? []);
  const emptyContent = `${HEADER}\nimport type { ComponentType } from 'react';\n\nexport const PAGE_WIDGETS: Record<string, ComponentType[]> = {};\n`;

  if (widgets.length === 0) {
    writeFileSync(resolve(outDir, 'module-page-widgets.ts'), emptyContent);
    return;
  }

  // Group by slot
  const slots = new Map<string, typeof widgets>();
  for (const w of widgets) {
    const list = slots.get(w.slot) ?? [];
    list.push(w);
    slots.set(w.slot, list);
  }

  const imports = widgets
    .map((w) => `import { ${w.name} } from '${w.from}';`)
    .join('\n');

  const entries = [...slots.entries()]
    .map(([slot, items]) => `  '${slot}': [${items.map((w) => w.name).join(', ')}],`)
    .join('\n');

  writeFileSync(
    resolve(outDir, 'module-page-widgets.ts'),
    `${HEADER}\nimport type { ComponentType } from 'react';\n\n${imports}\n\nexport const PAGE_WIDGETS: Record<string, ComponentType[]> = {\n${entries}\n};\n`,
  );
}

function generateDashboardWidgets(modules: ModuleConfig[]) {
  const widgets = modules.flatMap((m) => m.dashboardWidgets ?? []);
  const typeImports = `import type { ComponentType, ReactNode } from 'react';\nimport type { DashboardWidgetDef } from '@/core/config/dashboard-widgets';`;

  if (widgets.length === 0) {
    writeFileSync(
      resolve(outDir, 'module-dashboard-widgets.ts'),
      `${HEADER}\n${typeImports}\n\nexport const MODULE_DASHBOARD_WIDGETS: DashboardWidgetDef[] = [];\n\nexport const MODULE_DASHBOARD_WIDGET_COMPONENTS: Record<string, ComponentType<{ dragHandle?: ReactNode }>> = {};\n`,
    );
    return;
  }

  const imports = widgets
    .map((w) => `import { ${w.name} } from '${w.from}';`)
    .join('\n');

  const defEntries = widgets
    .map((w) => `  { id: '${w.id}', label: '${w.label}', colSpan: ${w.colSpan}, minSpan: ${w.minSpan}, maxSpan: ${w.maxSpan}, defaultVisible: ${w.defaultVisible} },`)
    .join('\n');

  const compEntries = widgets
    .map((w) => `  '${w.id}': ${w.name},`)
    .join('\n');

  writeFileSync(
    resolve(outDir, 'module-dashboard-widgets.ts'),
    `${HEADER}\n${typeImports}\n\n${imports}\n\nexport const MODULE_DASHBOARD_WIDGETS: DashboardWidgetDef[] = [\n${defEntries}\n];\n\nexport const MODULE_DASHBOARD_WIDGET_COMPONENTS: Record<string, ComponentType<{ dragHandle?: ReactNode }>> = {\n${compEntries}\n};\n`,
  );
}

function generateSeeds(modules: ModuleConfig[]) {
  const seeds = modules.flatMap((m) => m.seed ?? []);

  if (seeds.length === 0) {
    // Must match the populated branch's interface exactly — init.ts consumes
    // `hasData` and the 3-arg `fn` signature regardless of seed count.
    writeFileSync(
      resolve(outDir, 'module-seeds.ts'),
      `${HEADER}\nimport type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';\n\nexport interface SeedContext {\n  userIds: string[];\n  orgIds: string[];\n}\n\nexport interface ModuleSeed {\n  label: string;\n  fn: (db: PostgresJsDatabase, superadminUserId: string, context?: SeedContext) => Promise<{ userIds?: string[]; orgIds?: string[] }>;\n  hasData?: (db: PostgresJsDatabase) => Promise<boolean>;\n}\n\nexport const MODULE_SEEDS: ModuleSeed[] = [];\n`,
    );
    return;
  }

  const importNames = new Set<string>();
  const importLines: string[] = [];

  for (const s of seeds) {
    if (!importNames.has(s.name)) {
      const extras = s.hasDataCheck ? `, ${s.hasDataCheck}` : '';
      importLines.push(`import { ${s.name}${extras} } from '${s.from}';`);
      importNames.add(s.name);
      if (s.hasDataCheck) importNames.add(s.hasDataCheck);
    }
  }

  const imports = importLines.join('\n');

  const entries = seeds
    .map((s) => {
      const hasDataPart = s.hasDataCheck ? `, hasData: ${s.hasDataCheck}` : '';
      return `  { label: '${s.label}', fn: ${s.name}${hasDataPart} },`;
    })
    .join('\n');

  const content = `${HEADER}
import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';

${imports}

export interface SeedContext {
  userIds: string[];
  orgIds: string[];
}

export interface ModuleSeed {
  label: string;
  fn: (db: PostgresJsDatabase, superadminUserId: string, context?: SeedContext) => Promise<{ userIds?: string[]; orgIds?: string[] }>;
  hasData?: (db: PostgresJsDatabase) => Promise<boolean>;
}

export const MODULE_SEEDS: ModuleSeed[] = [
${entries}
];
`;

  writeFileSync(resolve(outDir, 'module-seeds.ts'), content);
}

function generateNav(modules: ModuleConfig[]) {
  const navItems = modules.flatMap((m) => m.navItems ?? []);

  if (navItems.length === 0) {
    writeFileSync(
      resolve(outDir, 'module-nav.ts'),
      `${HEADER}\nexport interface ModuleNavItem {\n  groupId: string;\n  name: string;\n  href: string;\n  icon: string;\n}\n\nexport const MODULE_NAV_ITEMS: ModuleNavItem[] = [];\n`,
    );
    return;
  }

  const entries = navItems
    .map((n) => `  { groupId: '${n.groupId}', name: '${n.name}', href: '${n.href}', icon: '${n.icon}' },`)
    .join('\n');

  const content = `${HEADER}
export interface ModuleNavItem {
  groupId: string;
  name: string;
  href: string;
  icon: string;
}

export const MODULE_NAV_ITEMS: ModuleNavItem[] = [
${entries}
];
`;

  writeFileSync(resolve(outDir, 'module-nav.ts'), content);
}

function generateMcp(modules: ModuleConfig[]) {
  const refs = modules.flatMap((m) => m.mcpTools ?? []);
  const inits = [...new Set(modules.flatMap((m) => m.mcpInit ?? []))];
  const outPath = resolve(outDir, 'module-mcp.ts');

  // Side-effect imports: registrations the MCP layer consumes (key verifier
  // etc). These MUST live in this file — MCP auth loads it lazily so the
  // registration lands in the Next.js route bundle's module graph.
  const initLines = inits.map((p) => `import '${p}';`).join('\n');

  // Collect composite-tool import lines + spreads, deduping (name, from) pairs.
  const seen = new Set<string>();
  const importLines: string[] = [];
  const spreads: string[] = [];
  for (const ref of refs) {
    const key = `${ref.name}@${ref.from}`;
    if (seen.has(key)) continue;
    seen.add(key);
    importLines.push(`import { ${ref.name} } from '${ref.from}';`);
    spreads.push(`  ...${ref.name},`);
  }

  const content = `${HEADER}
import type { ResolvedMcpTool } from '@/core/lib/mcp/types';
${initLines ? `\n${initLines}\n` : ''}${importLines.length ? `\n${importLines.join('\n')}\n` : ''}
export const moduleMcpTools: ResolvedMcpTool[] = [
${spreads.join('\n') || '  // No composite tools registered'}
];
`;

  writeFileSync(outPath, content);
}

main().catch((err) => {
  console.error('Module sync failed:', err);
  process.exit(1);
});
